apiVersion: v1test
kind: Application
metadata:
  name: my_test_application_nginx
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/eliecerecology/argocdtest.git
    targetRevision: HEAD
    path: dev2
  destination: 
    server: https://kubernetes.default.svc
    namespace: mynginxapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true