apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocdtest
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/eliecerecology/argocdtest.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: myOllamaApp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true