apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: argocdtest
  name: myOllamaApp
  namespace: myOllamaApp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myOllamaApp
  template:
    metadata:
      labels:
        app: myOllamaApp
    spec:
      containers:
        - image: ollama/ollama
          name: myOllamaApp
          ports:
            - containerPort: 8080
