apiVersion: apps/v1
kind: Deployment
metadata:
  name: myOllamaApp
spec:
  selector:
    matchLabels:
      app: myOllamaApp
  replicas: 2
  template:
    metadata:
      labels:
        app: myOllamaApp
    spec:
      containers:
      - name: myOllamaApp
        image: ollama/ollama
        ports:
        - containerPort: 8080
