apiVersion: apps/v1
kind: Deployment
metadata:
  name: myollamaapp
spec:
  selector:
    matchLabels:
      app: myollamaapp
  replicas: 2
  template:
    metadata:
      labels:
        app: myollamaapp
    spec:
      containers:
      - name: ollama
        image: ollama/ollama:latest # Update with the correct Ollama image
        ports:
        - containerPort: 11434
